# Generated by Django 5.2.1 on 2025-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('WORK', 'Work'), ('MEETING', 'Meeting'), ('BIRTHDAY', 'Birthday')], max_length=20),
        ),
    ]
